services:
  - type: web
    name: eduscriptai
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_PRINT_TELEMETRY_MESSAGE
        value: false
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: eduscriptai-db
          property: connectionString 